[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'nodejs_20', 'nginx']

[phases.install]
cmds = [
    'composer install --no-dev --optimize-autoloader',
    'npm install -f',
    'npm run build'
]

[phases.build]
cmds = [
    'php artisan key:generate --force',
    'mkdir -p storage/framework/{sessions,views,cache}',
    'mkdir -p storage/logs',
    'mkdir -p bootstrap/cache',
    'chmod -R 775 storage bootstrap/cache',
    'php artisan config:cache',
    'php artisan route:cache',
    'php artisan view:cache'
]

[start]
cmd = 'php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT'